# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Projects/GameMan/GameMan/GameMan.srcs/sources_1/ip/bram_32k_rom/bram_32k_rom.xci
# IP: The module: 'bram_32k_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Projects/GameMan/GameMan/GameMan.gen/sources_1/ip/bram_32k_rom/bram_32k_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_32k_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/Projects/GameMan/GameMan/GameMan.srcs/sources_1/ip/bram_32k_rom/bram_32k_rom.xci
# IP: The module: 'bram_32k_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Projects/GameMan/GameMan/GameMan.gen/sources_1/ip/bram_32k_rom/bram_32k_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_32k_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
