set_property SRC_FILE_INFO {cfile:f:/Projects/gb80/gb80.gen/sources_1/ip/bram_32k_rom/bram_32k_rom/bram_32k_rom_in_context.xdc rfile:../../../../../gb80.gen/sources_1/ip/bram_32k_rom/bram_32k_rom/bram_32k_rom_in_context.xdc id:1 order:EARLY scoped_inst:rom/unit} [current_design]
set_property SRC_FILE_INFO {cfile:f:/Projects/gb80/gb80.gen/sources_1/ip/bram_main_ram/bram_main_ram/bram_main_ram_in_context.xdc rfile:../../../../../gb80.gen/sources_1/ip/bram_main_ram/bram_main_ram/bram_main_ram_in_context.xdc id:2 order:EARLY scoped_inst:mram/unit} [current_design]
set_property SRC_FILE_INFO {cfile:F:/Projects/gb80/gb80.srcs/constrs_1/imports/new/lab_4.xdc rfile:../../../../../gb80.srcs/constrs_1/imports/new/lab_4.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins rom/unit/clka]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells rom/unit]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins mram/unit/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins mram/unit/clkb]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mram/unit]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells rom/unit]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mram/unit]
