# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Projects/gb80/gb80.srcs/sources_1/ip/bram_main_ram/bram_main_ram.xci
# IP: The module: 'bram_main_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Projects/gb80/gb80.gen/sources_1/ip/bram_main_ram/bram_main_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_main_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/Projects/gb80/gb80.srcs/sources_1/ip/bram_main_ram/bram_main_ram.xci
# IP: The module: 'bram_main_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Projects/gb80/gb80.gen/sources_1/ip/bram_main_ram/bram_main_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_main_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
